# Generated by Django 4.0.6 on 2022-07-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_customuser_managers_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sign_up_type',
            field=models.CharField(default='email', max_length=11, verbose_name='sign up type'),
            preserve_default=False,
        ),
    ]
