# Generated by Django 4.0.6 on 2022-07-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_customuser_sign_up_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that email or phone number already exists.'}, help_text='Required. valid email or phone number.', max_length=255, unique=True, verbose_name='email or phone number'),
        ),
    ]
