# Generated by Django 4.0.6 on 2022-07-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_verified',
            new_name='email_is_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_is_verified',
            field=models.BooleanField(default=False, verbose_name='verify status'),
        ),
    ]
