# Generated by Django 4.0.6 on 2022-07-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_rename_is_verified_customuser_email_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='phone number'),
        ),
    ]
